Controllers/PorudzbineController.cs
using EPromet.Models;
using Microsoft.AspNetCore.Mvc;

namespace EPromet.Controllers
{
    public class PorudzbineController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IWebHostEnvironment putanja;
        private IEnumerable<Porudzbina> porudzbine;


        public PorudzbineController(ILogger<HomeController> logger, IWebHostEnvironment hostEnvironment)
        {
            _logger = logger;
            putanja = hostEnvironment;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NovePorudzbine()
        {
            porudzbine = DatabaseModel.UcitajPorudzbine(putanja);
            List<Porudzbina> porudzbineTemp = new List<Porudzbina>();
            foreach (Porudzbina por in porudzbine)
            {
                if (por.Status == Porudzbina.EStatus.NA_CEKANJU)
                {
                    porudzbineTemp.Add(por);
                }

            }


            return View(porudzbineTemp);
        }

        public IActionResult MojePorudzbine()
        {
            porudzbine = DatabaseModel.UcitajPorudzbine(putanja);
            List<Porudzbina> porudzbineTemp = new List<Porudzbina>();
            foreach (Porudzbina por in porudzbine)
            {
                if (por.IdDostavljaca==((Korisnik)Global.User).Id && por.Status == Porudzbina.EStatus.IZVRSENA)
                {
                    porudzbineTemp.Add(por);
                }

            }


            return View(porudzbineTemp);
        }

        public IActionResult PrethodnePorudzbine()
        {
            porudzbine = DatabaseModel.UcitajPorudzbine(putanja);
            List<Porudzbina> porudzbineTemp = new List<Porudzbina>();
            foreach (Porudzbina por in porudzbine)
            {
                if (por.IdKorisnika==((Korisnik)Global.User).Id && por.Status == Porudzbina.EStatus.IZVRSENA)
                {
                    porudzbineTemp.Add(por);
                }

            }


            return View(porudzbineTemp);
        }

        public IActionResult SvePorudzbine()
        {
            porudzbine = DatabaseModel.UcitajPorudzbine(putanja);



            return View(porudzbine);
        }

        public IActionResult PrihvatiPorudzbinu(int id)
        {
            Porudzbina por = new Porudzbina();
            porudzbine = DatabaseModel.UcitajPorudzbine(putanja);
            foreach (Porudzbina p in porudzbine)
            {
                if(p.Id == id)
                {
                    por = p;
                    por.Status = Porudzbina.EStatus.NEIZVRSENA;
                    por.IdDostavljaca = ((Korisnik)Global.User).Id;
                    DatabaseModel.UpdatePorudzbine(por, putanja);
                }
            }
            Global.Porudzbina = por;

            return RedirectToAction("Index","Shop");
        }

    }
}

Controllers/ProizvodiController.cs
using EPromet.Models;
using Microsoft.AspNetCore.Mvc;

namespace EPromet.Controllers
{
    public class ProizvodiController : Controller
    {

        private IWebHostEnvironment putanja;


        public ProizvodiController(IWebHostEnvironment environment)
        {
            putanja = environment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Proizvod p)
        {
            DatabaseModel.SacuvajProizvod(p, putanja);

            return RedirectToAction("Index","Shop");
        }
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EPromet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EPromet.styles.css" asp-append-version="true" />
</head>



<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 align-content-center">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Shop" asp-action="Index">EPromet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Global.UserRole != null)
                        {
                            @if (Global.UserRole.ToString() == "KORISNIK")
                           {          
                               if(Global.Porudzbina!=null && ((Porudzbina)Global.Porudzbina).Status.ToString() == "NEPOTVRDJENA")
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Korpa">Korpa</a>
                                    </li>
                                }
                                if (Global.Porudzbina!=null && ((Porudzbina)Global.Porudzbina).Status.ToString() != "NEPOTVRDJENA")
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="MojaPorudzbina">Trenutna porudzbina</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Porudzbine" asp-action="PrethodnePorudzbine">Prethodne porudzbine</a>
                                </li>
                           }
                            @if (Global.UserRole.ToString() == "ADMINISTRATOR")
                           {                               
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profil" asp-action="Verifikacija">Verifikacije</a>
                                </li>                      
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Porudzbine" asp-action="SvePorudzbine">Sve porudzbine</a>
                                </li>                    
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Proizvodi" asp-action="Create">Dodavanje proizvoda</a>
                                </li>
                           }
                            @if (Global.UserRole.ToString() == "DOSTAVLJAC")
                           {      
                               if(Global.Porudzbina == null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Porudzbine" asp-action="NovePorudzbine">Nove porudzbine</a>
                                    </li>     
                                }    
                                if (Global.Porudzbina != null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="MojaPorudzbina">Trenutna porudzbina</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Porudzbine" asp-action="MojePorudzbine">Moje porudzbine</a>
                                </li>   
                           }
                        }
                    </ul>
                    @if (Global.UserRole == null)
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autentifikacija" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Autentifikacija" asp-action="Register">Register</a>
                            </li>
                        </ul> 
                   }
                   @if (Global.UserRole != null)
                  {
                     <ul class="navbar-nav ml-auto">                         
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profil" asp-action="Details">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autentifikacija" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                  }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EPromet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>